#include "Rendering/API/RenderContext.h"

namespace MARS
{
bool RenderContext::CheckCapability(GRAPHICSDEVICE_CAPABILITY Capability) const
{
	switch (Capability)
	{
		case GRAPHICSDEVICE_CAPABILITY_TESSELLATION:
		{
			return TESSELLATION;
		} break;

		case GRAPHICSDEVICE_CAPABILITY_CONSERVATIVE_RASTERIZATION:
		{
			return CONSERVATIVE_RASTERIZATION;
		} break;

		case GRAPHICSDEVICE_CAPABILITY_MULTITHREADED_RENDERING:
		{
			return MULTITHREADED_RENDERING;
		} break;

		case GRAPHICSDEVICE_CAPABILITY_RASTERIZER_ORDERED_VIEWS:
		{
			return RASTERIZER_ORDERED_VIEWS;
		} break;

		case GRAPHICSDEVICE_CAPABILITY_UNORDEREDACCESSTEXTURE_LOAD_FORMAT_EXT:
		{
			return UNORDEREDACCESSTEXTURE_LOAD_EXT;
		} break;

		default: break;
	}

	return false;
}

uint32 RenderContext::GetStride(FORMAT Val) const
{
	switch (Val)
	{
		case GRAPHICS::FORMAT_R32G32B32A32_FLOAT: return 16;

		case GRAPHICS::FORMAT_R32G32_FLOAT:
		case GRAPHICS::FORMAT_R32G32_UINT:
		case GRAPHICS::FORMAT_R32G32_SINT:
		case GRAPHICS::FORMAT_R16G16B16A16_FLOAT: return 8;

		case GRAPHICS::FORMAT_R11G11B10_FLOAT:
		case GRAPHICS::FORMAT_R16G16_FLOAT:
		case GRAPHICS::FORMAT_R16G16_UINT:
		case GRAPHICS::FORMAT_R16G16_SINT:
		case GRAPHICS::FORMAT_R32_FLOAT:
		case GRAPHICS::FORMAT_R32_UINT:
		case GRAPHICS::FORMAT_R8G8B8A8_UINT:
		case GRAPHICS::FORMAT_R8G8B8A8_SINT:
		case GRAPHICS::FORMAT_R8G8B8A8_UNORM:
		case GRAPHICS::FORMAT_R8G8B8A8_SNORM:
		case GRAPHICS::FORMAT_R10G10B10A2_UNORM: return 4;

		case GRAPHICS::FORMAT_R16_FLOAT:
		case GRAPHICS::FORMAT_R16_UINT:
		case GRAPHICS::FORMAT_R16_SINT:
		case GRAPHICS::FORMAT_R16_UNORM:
		case GRAPHICS::FORMAT_R16_SNORM: return 2;

		case GRAPHICS::FORMAT_R8_TYPELESS:
		case GRAPHICS::FORMAT_R8_UNORM:
		case GRAPHICS::FORMAT_R8_SNORM:
		case GRAPHICS::FORMAT_R8_UINT:
		case GRAPHICS::FORMAT_R8_SINT:
		case GRAPHICS::FORMAT_A8_UNORM: return 1;

		default:
		{
			Assert(0, "Unsupported Format")
		} break;	
	}

	return 16;
}

bool RenderContext::IsUnorm(FORMAT Val) const
{
	switch (Val)
	{
		case GRAPHICS::FORMAT_R8G8B8A8_UNORM:
		case GRAPHICS::FORMAT_R10G10B10A2_UNORM:
		case GRAPHICS::FORMAT_R16_UNORM:
		case GRAPHICS::FORMAT_A8_UNORM:
		case GRAPHICS::FORMAT_R8_UNORM: return true;
	}

	return false;
}
}